<?php

namespace lray138\G2\Either;

use lray138\G2\Common\{
    GonadTrait,
    GetPropTrait 
};

use lray138\G2\Either;
use function lray138\G2\dump;

final class Right extends Either
{
    use GonadTrait;

    // I forgot I did that ;)
    // (and it was stupid)  
    // I'm not sure why I did that, but I'm not going to remove it
    // because I'm lazy and I don't want to break anything
    // and I'm not sure if it's even used anywhere
    // so I'm just going to leave it here
    // and I'm going to add a comment to remind me why I did it
    // and to remind me to remove it later

    // uhh the above was auto generated by Cursor, weird....

    //use GetPropTrait;

    public function fold(callable $_, callable $f)
    {
        return $f($this->extract());
    }

    public function map(callable $f): Either
    {
        return Right::of($f($this->extract()));
    }

    public function bind(callable $f): Either
    {
        return $f($this->extract());
    }

    public function getOrLeft() {
        return $this->extract();
    }

    public function call($method, ...$args) {
        $value = $this->extract();

        if (is_object($value) && method_exists($value, $method)) {
            try {
                return Right::of($value->$method(...$args));
            } catch (\Throwable $e) {
                return Left::of($e->getMessage());
            }
        }

        return Left::of("Method `$method` does not exist on " . (is_object($value) ? get_class($value) : gettype($value)));
    }

    public function dump() {
        dump($this);
        return $this;
    }

    public function getOrElse($value) {
        return $this->extract();
    }
}